config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  resources :posts
  resources :post do
    resources :comments
    resources :upvotes, only: :create
    resource :downvotes, only: :create
  end
  resources :users
  resources :comments

end

app/views/shared/_comment.html.erb
        <% post.comments.each do |comment| %>
             <div class="panel panel-default">
                    <div class="panel-body">
                            
                            <%= link_to comment.user_name,  user_path(comment.user_id) %>: <%= comment.text %>
                            <% if comment.user == current_user %> 
                                <%= link_to 'Edit', edit_post_comment_path(post_id: comment.id, id: comment.id), method: :get, render: true %>
                                <%= link_to 'Delete', post_comment_path(post_id: post.id, id: comment.id), method: :delete %>
                            
                            <% end %>
                     </div>
             </div>
        <% end %>
    
        <hr>
        
        
    
        <% if user_signed_in? %>
            <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post,render: true, html: { class:'form-horizontal'} do |f| %>
                <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
                <%#= <textarea aria-label="Add a comment..." class="bilrf" placeholder="Add a comment..." style="height:36px;"></textarea> %>
                <%= f.submit 'Post', class: 'btn btn-primary btn-block', render: true %>
            <% end %>
        <% end %> 
        
        

app/views/shared/_footer.html.erb
<div class="g71f5" style="max-width:935px;">
    <span class="gmap">© 2017 Instapost</span>
</div>

app/views/shared/_header.html.erb
<%= image_tag post.user_photo,class:'prof_pic_small' %>
<!--In this case, post is the placeholder variable in the each loop, representing a single Post from the @posts collection. -->
<!-- Since Post belongs to User, Rails allows you to call the user that owns the Post by doing post.user. -->
<%= link_to post.user_name, user_path(post.user_id) %> 
<span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>

app/views/shared/_likes.html.erb
<% if user_signed_in? %>
            <span class="post_like">
                <% if current_user.voted_up_on? post %>
                    <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %>
                    <%#= with the remote: true, it processed the request as JS, and without it, it process the request as HTML. %>
                    <% else %>
                        <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe,post_upvotes_path(post.id), method: :post, remote: true %>
                    <% end %>
                  <%= pluralize post.get_likes.size, "like" %>
            </span>
        

        <% else %>
        <span class="post_like">
            <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
        </span>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <div class="row">
    <div class = "col-lg-6 col-lg-offset-3">
      <div class="row">
        <div class="nav_wrapper">
            
              <div class="col-xs-6">
                <div class="socio-icons">
                    <%= link_to '<i class="fa fa-instagram" aria-hidden="true"></i>'.html_safe, root_path %>
                </div>
                    <span class="pull-left brand"><%= link_to 'Instapost', root_path %></span>
              </div>
    
              <div class="col-xs-6">
                  <% if user_signed_in? %>
                    <span class="nav_links pull-right"><%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i>'.html_safe, destroy_user_session_path, method: :delete %></span>
                    <span class="nav_links pull-right"><%= link_to '<i class="fa fa-plus" aria-hidden="true"></i>'.html_safe, new_post_path %></span>
                    <span class="nav_links pull-right"><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_user_registration_path %></span>
                  <% else %>
                    <span class="nav_links pull-right"><%= link_to 'Sign Up', new_user_registration_path %></span>
                    <span class="nav_links pull-right"><%= link_to 'Log In', new_user_session_path %></span>
                  <% end %>
              </div>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_post.html.erb
<%= image_tag post.photo, class: 'photo' %>
                <% if post.user == current_user %>
                    <div class="panel panel-default">
                            <div class="post_body">
                                 <%= post.description %>
                            </div>
                            
                        <div class="panel-body">
                                <button type="button" class="btn btn-default">
                                    <%= link_to 'Edit Post', edit_post_path(post.id) %>
                                </button>
                                <button type="button" class="btn btn-default">
                                    <%= link_to 'Delete Post', post_path(post.id), method: :delete %>
                                </button>
                                <button type="button" class="btn btn-default">
                                    <%= link_to 'Go to post', post_path(post.id) %> 
                                </button>
                        </div>
                    </div>
                    
                <% else %>
                <div class="panel panel-default">
                            <div class="post_body">
                                 <%= post.description %>
                            </div>
                        <div class="panel-body">
                            <button type="button" class="btn btn-default">
                                <%= link_to 'Go to post', post_path(post.id) %> 
                            </button>
                        </div>
                    </div>
                <% end %>